add env
pinzimpossible/AT pull request #1
Opened 2024-11-27 13:09 UTC by pinzimpossible

Create a PR for env.properties

2024-11-27 13:32 UTC, hieuln1991 commented on src/test/java/base/readENV.java
> +            FileInputStream fileInputStream = new FileInputStream("src/test/java/env/env.properties");
Change thành file name variable. vd: String name = env + "_config.properties"
define 2 config.properties: stage, prod

2024-11-27 13:35 UTC, QAonTheAir requested changes

2024-11-27 13:35 UTC, hieuln1991 commented on src/test/java/page/loginPage.java
> +        driver.get(readENV.get("env"));
function load env data phải dc viết trong base test, dùng anotation: BeforeSuite.

2024-12-11 13:10 UTC, pinzimpossible commented
Fix comment + add ex4

2024-12-30 13:16 UTC, merged